_target_: src.models.self_supervised.simclr.SimCLR

lr: 0.0001
backbone: resnet10
weight_decay: 0.0001
epoch: ${trainer.pretrain.max_epochs}
batch_size: ${datamodule.self_supervised.batch_size}

# method specific parameters
proj_output_dim: 128
proj_hidden_dim: 64
temperature: 1.0