_target_: src.models.self_supervised.exact_ssl_module.ExactSSLModule
backbone: resnet10
lr: 0.0001
weight_decay: 0.0001
optim_algo: "Adam"
epoch: ${trainer.max_epochs}
batch_size: ${datamodule.batch_size}
