_target_: src.models.supervised.exact_module.ExactLitModule
lr: 0.0001
weight_decay: 0.001
batch_size: 32

net:
  _target_: src.models.components.resnets.ResNet
  num_classes: 2 # number of classes
  in_channels: 1 # number of input channels
  layers: [1, 1, 1, 1] # number of conv layers in each residual block
  block:
    _target_: hydra.utils.get_class
    path: src.models.components.resnets.BasicBlock
