_target_: src.models.supervised.test_module.ExacTestFinetuner

test_module:
  _target_: src.models.self_supervised.finetuner_module.ExactFineTuner
  num_classes: 2
  semi_sup: True
  ckpt_path: null
  in_features: 512
  hidden_dim: null
  backbone:
    _target_: src.models.self_supervised.vicreg.vicreg_module.VICReg


ckpt_path: null
backbone_ckpt_path: null
optim_algo: "Adam"
weight_decay: 1e-6
learning_rate: 0.0001 # learning rate of finetuning step

num_classes: 2
semi_sup: False
batch_size: ${datamodule.batch_size}
epochs: ${trainer.max_epochs}

