
_target_: src.callbacks.online_evaluation.OnlineEvaluation

defaults:
  - /datamodule@datamodule: supervised.yaml

num_classes: 2
num_epochs: 50
lr: 1e-4
weight_decay: 1e-6
patience: 10
evaluate_every_n_epochs: 10
reinit_every_epoch: True
log_best_only: False