_target_: src.datamodules.exact_datamodule.ExactCoreDataModule

batch_size: 5
num_workers: 4

patch_view_config:
  _target_: exactvu.data.core.PatchViewConfig
  patch_size: [5, 5]
  patch_strides: [1,1]
  subpatch_size: [1,1]
  needle_region_only: True
  prostate_region_only: True
  prostate_intersection_threshold: 0.9
  needle_intersection_threshold: 0.6

splits_config:
  _target_: exactvu.data.splits.SplitsConfig
  cohort_specifier: "UVA600"
  resample_train_val: True
  split_seed: 26
  train_val_ratio: 0.25
  balance_classes: True
  benign_cores_selection_seed: 0

minimum_involvement: 0.4
return_metadata: True

#use_augmentations: False
#aug_prob: 0.4 # probability of augmentations

#random_erasing: True
#random_invert: False
#random_horizontal_flip: True
#random_vertical_flip: True
#random_affine_translation: [0.2, 0.2]
#random_affine_rotation: 0
#random_affine_shear: [0, 0, 0, 0]
#random_resized_crop: False
#random_resized_crop_scale: [0.7, 1]

balance_classes_train: True
#normalize_mode: instance
#normalize_type: min-max
#normalize_truncate: True
